# Generated by Django 2.1.7 on 2019-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleClientes', '0002_auto_20190310_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
